default:
    interruptible: true

stages:
  - setup
  - validate
  - build
  - deploy
  - changelog

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "tag"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

Configure Build:
  tags:
  - infra
  stage: setup
  timeout: 5m
  script:
    - ci/setup_build.sh
  artifacts:
    reports:
      dotenv: .dotenv


Build PC/Linux:
  tags:
  - amd64
  - linux
  stage: build
  timeout: 20m
  script:
    - ci/build_dist_amd64_linux.sh
  artifacts:
    paths:
      - als-$ALS_VERSION_STRING.run


Build RaspBerry/Linux:
  tags:
  - arm64
  - linux
  stage: build
  timeout: 20m
  script:
    - ci/build_dist_arm64_linux.sh
  artifacts:
    paths:
      - als-$ALS_VERSION_STRING.tgz


Build Mac/Intel:
  tags:
  - amd64
  - mac
  stage: build
  timeout: 20m
  script:
    - ci/build_dist_amd64_osx.sh
  artifacts:
    paths:
      - als-$ALS_VERSION_STRING.dmg


Build PC/Windows:
  tags:
  - amd64
  - win
  stage: build
  timeout: 20m
  script:
    - sh ci/build_dist_amd64_win.sh
  artifacts:
    paths:
      - als-$ALS_VERSION_STRING.exe
