default:
    interruptible: true

stages:
  - setup
  - validate
  - build
  - deploy
  - changelog

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "tag"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

Configure Build:
  tags:
  - infra
  stage: setup
  timeout: 5m
  script:
    - ci/builds/setup_build.sh
  artifacts:
    reports:
      dotenv: .dotenv
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Build PC/Linux:
  tags:
  - amd64
  - linux
  stage: build
  timeout: 1h
  script:
    - ci/builds/build_dist_amd64_linux.sh
  artifacts:
    expose_as: 'ALS for Linux amd64'
    paths:
      - als-$ALS_VERSION_STRING.run
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Build RaspBerry/Linux:
  tags:
  - arm64
  - linux
  stage: build
  timeout: 1h
  script:
    - ci/builds/build_dist_arm64_linux.sh
  artifacts:
    expose_as: 'ALS for Linux arm64'
    paths:
      - als-$ALS_VERSION_STRING.tgz
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Build Mac/Intel:
  tags:
  - amd64
  - mac
  stage: build
  timeout: 1h
  script:
    - ci/builds/build_dist_amd64_osx.sh
  artifacts:
    expose_as: 'ALS for OSX amd64'
    paths:
      - als-$ALS_VERSION_STRING-amd64.dmg
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Build Mac/ARM:
  tags:
  - arm64
  - mac
  stage: build
  timeout: 1h
  script:
    - ci/builds/build_dist_arm64_osx.sh
  artifacts:
    expose_as: 'ALS for OSX arm64'
    paths:
      - als-$ALS_VERSION_STRING-arm64.dmg
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Build PC/Windows:
  tags:
  - amd64
  - win
  stage: build
  timeout: 1h
  script:
    - sh ci/builds/build_dist_amd64_win.sh
  artifacts:
    expose_as: 'ALS for Windows amd64'
    paths:
      - als-${ALS_VERSION_STRING}_Setup.exe
  rules:
    - changes:
        - .gitlab-ci.yml
        - ci/**/*
        - src/**/*
        - analyzer/**/*
        - utils/**/*
        - tests/**/*
        - setup.py
        - setup.cfg
        - requirements.txt
    - when: never


Deploy nightlies:
  tags:
    - infra
  stage: deploy
  script: ci/deploy/deploy_nightlies.sh
  environment:
    name: Nightlies
    url: https://als-app.org/nightlies
  rules:
    - if: $CI_SCHEDULE_ID == "1"

Deploy website staging:
  tags:
    - infra
  stage: deploy
  script: ci/deploy/deploy_website_staging.sh
  environment:
    name: staging
    url: https://next.als-app.org/
  rules:
    - changes:
        - website/**/*
