baseURL = "https://next.als-app.org/"
languageCode = "fr"
title = "Astro Live Stacker"
theme = "docsy"
publishDir = "public"
enableRobotsTXT = true
defaultContentLanguage = "fr"  # Retain this, but avoid the problematic line in the `languages` section

[params]
  docs = true
  disableBreadcrumb = false
  disableFeedback = true
  searchIndexInMemory = true
  custom_css = "css/custom.css"

[params.ui]
  navbarVariant = "dark"
  sidebarVariant = "dark"
  primaryColor = "#ff0000"
  primaryDarkColor = "#8b0000"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.fr]
    weight = 1
    languageName = "Français"
    contentDir = "content/fr"

    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/about/"
      weight = 10

    [[languages.fr.menu.main]]
      identifier = "docs"
      name = "Documentation"
      url = "/docs/"
      weight = 20

  [languages.en]
    weight = 2
    languageName = "English"
    contentDir = "content/en"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "docs"
      name = "Docs"
      url = "/en/docs/"
      weight = 20

[params.languageswitcher]
  enable = true
  style = "dropdown"
