# Basic Site Configuration
baseURL = "https://next.als-app.org/"
languageCode = "fr"
title = "Astro Live Stacker"
theme = "docsy"
publishDir = "public"
enableRobotsTXT = true
defaultContentLanguage = "fr"
enableGitInfo = true

# Site Parameters
[params]
  docs = true
  disableBreadcrumb = false
  disableFeedback = true
  searchIndexInMemory = true
  favicon = "/images/favicon.ico"
  logo = "/images/als_logo_256.png"

  # UI Customization
  [params.ui]
    navbarVariant = "dark"
    sidebarVariant = "dark"
    primaryColor = "#ff0000"
    primaryDarkColor = "#8b0000"

  # Language Switcher
  [params.languageswitcher]
    enable = true
    style = "dropdown"

# Markup Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Language Configuration
[languages]
  # French Configuration
  [languages.fr]
    weight = 1
    languageName = "Français"
    contentDir = "content/fr"

    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/about/"
      weight = 10

    [[languages.fr.menu.main]]
      identifier = "contributors"
      name = "Contributeurs"
      url = "/contributors/"
      weight = 15

    [[languages.fr.menu.main]]
      identifier = "docs"
      name = "Documentation"
      url = "/docs/"
      weight = 20

  # English Configuration
  [languages.en]
    weight = 2
    languageName = "English"
    contentDir = "content/en"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "contributors"
      name = "Contributors"
      url = "/en/contributors/"
      weight = 15

    [[languages.en.menu.main]]
      identifier = "docs"
      name = "Docs"
      url = "/en/docs/"
      weight = 20
