# Basic Site Configuration
baseURL = "https://next.als-app.org/"
languageCode = "fr"
title = "Astro Live Stacker"
theme = "docsy"
publishDir = "public"
enableRobotsTXT = true
enableGitInfo = true

# Site Parameters
[params]
  docs = true
  disableBreadcrumb = false
  disableFeedback = true
  searchIndexInMemory = true
  favicon = "/images/favicon.ico"
  logo = "/images/als_logo_256.png"

  # UI Customization
  [params.ui]
    navbarVariant = "dark"
    sidebarVariant = "dark"
    sidebar_menu_compact = false
    ul_show = 2
    sidebar_menu_foldable = true
    sidebar_cache_limit = 1000

  # Language Switcher
  [params.languageswitcher]
    enable = true
    style = "dropdown"

  # Version Configuration
  version_menu = "Version"
  version_menu_pagelinks = true
  [[params.versions]]
    url = "/docs/v0.7/"
    version = "v0.7"
  # Add future versions here
  # [[params.versions]]
  #   url = "/docs/v1.0/"
  #   version = "v1.0"

# Markup Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
  [markup.highlight]
    lineNos = true
    style = 'onedark'



# Language Configuration
[languages]
  # French Configuration
  [languages.fr]
    weight = 1
    languageName = "Français"
    contentDir = "content/fr"

    [[languages.fr.menu.main]]
      identifier = "about"
      name = "Projet"
      url = "/fr/about/"
      weight = 10

    [[languages.fr.menu.main]]
      identifier = "contributors"
      name = "Contributeurs"
      url = "/fr/contributors/"
      weight = 15

    [[languages.fr.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/blog/"
      weight = 18

    [[languages.fr.menu.main]]
      identifier = "docs"
      name = "Documentation"
      url = "/fr/docs/v0.7/"
      weight = 20

  # English Configuration
  [languages.en]
    weight = 2
    languageName = "English"
    contentDir = "content/en"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "contributors"
      name = "Contributors"
      url = "/contributors/"
      weight = 15

    [[languages.en.menu.main]]
      identifier = "docs"
      name = "Docs"
      url = "/docs/v0.7/"
      weight = 20
